### ISSUE TITLE
Project Support Request: DNN Platform

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#103]
### Please fill in the information below:
- **Project Name:** DNN Platform
- **Due by:** ASAP 
- **Description:** We need to get info@danielvaladas.com added to our DevOps account as his existing account is having issues and Microsoft support is recommending this new identity being added.  

He should have the same permissions as Myself and Brian Dukes in the organization.

**Comment by clairernovotny** [comment]
That email/account is already there, not sure I'm following?

**Comment by clairernovotny** [comment]
Should be all set now.

**Comment by valadas** [comment]
Hi @clairernovotny , it looks like it is showing my old email.
![image](https://user-images.githubusercontent.com/6371568/94297573-ba768a80-ff32-11ea-952c-0349b768c641.png)

Basically that email was tied to my ISP which is no longer available where I moved, I first change my email to info@danielvaladas.com in my microsoft accountwhich is not tied to any isp. It only changed in some places and well it too Microsoft support sinca april to troubleshoop and get it resolved everywhere except here. If it is of any help for troubleshooting, what finaly worked was they switched my account to cloud active directory, then back in order to move my services to only the info@danielvaladas.com account.

It is fine everywhere except here https://dev.azure.com/dotnet/DNN and they told me someone with admin privileges would have to either switch that account or change the notification email... Ping me up if anything else might be of help.

Thanks.

**Comment by valadas** [comment]
Thanks @clairernovotny and @mitchelsellers it looks like I was missing an invite email which I found and clicked on. All looks nice now and this issue can be closed.

**Comment by valadas** [comment]
@clairernovotny The issue came back I am troubleshooting with a Mirosoft accounts technician and they say they need to get in touch with a Project Collection Administrator (PCA) ? Can we schedule something up with them.

My email is info@danielvaladas.com

Thanks

**Comment by clairernovotny** [comment]
I am the admin of that instance....

**Comment by valadas** [comment]
I know, can we setup a meeting? Can you email me to get you into that email thread with Microsoft or some such

**Comment by valadas** [comment]
Hi @clairernovotny did you get the email from me and Microsoft, I had no news for about a week, not sure if maybe that email got into your spam folder or what ?

**Comment by clairernovotny** [comment]
Closing due to age. Please reopen if there's still an issue.

**Comment by valadas** [comment]
Thanks Claire, the issue was resolved (kinda) with Microsoft
