### ISSUE TITLE
Project leaders support

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/projects#18]
@jongalloway mentioned in a recently closed issue on the project maturity post.

> .NET Foundation Leadership Structure
The project leaders don't have a formal place in the .NET Foundation leadership structure, which led to the above communication issue. Of course they should, they're community leaders, invested in the .NET Foundation's success, affected by policy and service changes, etc.
>
> The current structure includes a community elected board of directors, an executive director who reports to them and does the day to day work, two advisory groups (the Advisory Council and TSG / Corporate Sponsor group), and our new Action Groups. Before setting up the project leader slack, we didn't have a group discussion between project leaders, and they didn't operate as a body. Now that we have a cohesive group of project leaders, we need to figure out how to make that more official, have regular meetings, etc.
>
> So from the project leader perspective, it may seem baffling that we didn't run this by all of you. From an organizational perspective, we reviewed with the official leadership structure several times. Again, this was a miss on our part, and I apologize.

I want to start this issue to address that Jon mentioned above. 

Maybe introduce a new advisory group from the project leaders group?

**Comment by Aaronontheweb** [comment]
Reposting my feedback from https://github.com/dotnet-foundation/project-maturity-model/issues/48, per @glennawatson 's suggestion.

-------

Since I don't see a good repository for talking about how the .NET Foundation itself is run, I'm going to post this here.

I want to thank @jongalloway, @richlander, @JamesNK, @ImmoLandwerth and other Microsofties have done the thankless task of dealing with opinionated developers / malcontents like me in how this process has been rolled out thus far. One thing we can all agree on is how this proposal was rolled out and presented to the foundation memberships was disastrous and something all parties would prefer to avoid in the future.

I am intensely disinterested in using this thread for assigning blame to any individuals for how that happened, because that's a petty exercise in cruelty and belittlement.

What I am interested in discussing: how future ideas like this are socialized with the community and putting forth some suggestions that will help.

## .NET Foundation Stakeholders
There are, in my eyes, four key stakeholders in the .NET ecosystem:

1. The ultimate consumers of .NET, the developers building applications with OSS work;
2. The project developers and maintainers;
3. The businesses who support those project developers (can't have sustainability without them;) and
4. Microsoft, the platform creators.

To have an ecosystem that works, all four of these parties have to have the freedom to experiment with new ideas, designs, business models, and so on. The .NET Foundation is here to  align the interests of all four groups in service of building a better, more innovative, creative, and, most importantly, _fun_ ecosystem. We are all onboard with this.

The communication failure that occurred here, speaking as someone who was never in the room during the discussions and only heard about it when it was announced publicly, is that groups 2 and 3 were underrepresented in the maturity ladder discussions leading up to is announcement, despite them also being major cost-bearing parties in the event of its implementation. This is how I and, I gather from the comments thus far, many of the other project members feel.

## .NET Foundation "Initiatives"
Fundamentally, the proposal as it was presented from "day one" to the rest of the foundation was as a solution for a problem that is largely unknown and unheard of by those stakeholders, and an awfully heavy-handed solution at that.

In this respect, going forward the process for putting forth a foundation-wide initiative like this must start with socializing _agreement that there is a problem_ prior to working on a fix. When I see comments from @haacked (not picking on you, just using you as an example) like this:

> Unfortunately that's exactly what attackers are counting on these days. It's likely that a phishing attack enabled attackers to inject a remote code execution backdoor in bootstrap-sass. People trusted that package because it was adopted by many. I've written a series of posts on the topic of package security: https://haacked.com/archive/2019/06/11/package-manager-security/
> 
> Nothing is foolproof in protecting consumers, but as these attacks continue to be successful (and perhaps there are many that have been that we just don't know about), I think it's important to set some basic guidelines around good security practices.

I can absolutely see Phil, an original developer of NuGet and veteran Github employee, viewing package security as a critical ecosystem problem given his expertise. And he is not wrong. But would @ghuntley, myself, or a dozen other .NET project members say this is an issue of greater significance over day-to-day issues we deal with like sustainability? Probably not, and the people behind this proposal would have heard that _loud and clear_ prior to spending nights and weekends working on this.

I would propose that's what we start with in the future - we socialize the problems first, not their solutions. Let's not create a giant, heavily structured proposal on how to deal with a problem that may not be an actual problem yet; first we gather input from all four groups of stakeholders, widely and publicly, when it comes to ecosystem-wide issues.

I'm sure I'd be surprised to learn from Microsoft or other project members what some of their OSS problems are, but that's the right place for a "proposal" to begin in the future and it should be done in the open. 

Here's how we could have gone about starting this process, via an oversimplified example in the form of a Github issue / simple readme, written from the perspective of someone working on the .NET team at Microsoft:

---
### Initiative: broadening the adoption of third party OSS among large enterprises and Microsoft
Internally at Microsoft, among some of our large enterprise users (Fortune 500), and among some of our Microsoft Consulting partners, we have heard the feedback that they won't adopt any third party source code for the following reasons:

1. Lack of reproducible builds;
2. Unknown or untrustworthy package ownership;
3. Lack of bug triage and activity; and
4. Infrequent releases.

We're assessing the extent, scale, and possible solutions to this problem.

If you're a package developer who's lost a user due to this types of issues (not exactly, but in this vein) or if you're a developer who's had to decline use of a third party project because of this issue, what were the objections and how often does this happen?

---

Can we imagine how different this entire rollout would have looked if we started the discussion this way? I would have immediately chimed in with how I lost a deal with a big company because they wanted to stick with MSMQ (because Microsoft made it) as their preferred messaging technology or how I lost one with a massive insurance company because they're worried about intellectual property issues with _any_ OSS. 

I suspect we would have buy-in from all four groups within a short period of time that this is a real issue, given the shared and readily visible data from all four groups of stakeholders. Having access to new information at our finger tips that would help us see common recurring patterns that are bigger than any one stakeholder within the .NET Foundation umbrella.

From there, a proposal on what to do about this problem could be proposed by anyone on that issue, but ultimately the .NET Foundation director and the team would need to culminate that feedback into something with structure, which should be socialized again. After enough of that has passed, put it up for a vote to the board.

I'd be excited to participate in that kind of process, because I would finally have an avenue to address an ecosystem problem that is bigger than what I deal with, alone, every day - and I would welcome the opportunity to work with our colleagues to do something about it.

I hope you consider this in the spirit of constructive feedback and wanting to see the foundation achieve its goals.
