### ISSUE TITLE
Project Support Request: CoreWCF - CI/CD

### ISSUE THREAD

**Issue by jongalloway** [dotnet-foundation/projects#19]
### Please fill in the information below:
- **Project Name:** CoreWCF
- **Due by:**
- **Description:** Set up CI/CD on Azure DevOps

**Comment by jongalloway** [comment]
cc @mconnew @tibor19

**Comment by jongalloway** [comment]
I've created and invited you both to https://dev.azure.com/dotnet/CoreWCF. It's private for now, I'd recommend making it public if that's okay with you.

Next step is setting up automated build and package creation. Can you start on this using the docs below and ping if you need help?

- [ ] [Set up build pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops)
- [ ] [NuGet Package creation](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget)

**Comment by mconnew** [comment]
@jongalloway, Azure Dev Ops is getting really confused because apparently that triggered creating me a second work account. I have the friendly name alias account for my Microsoft work email and now I can't do anything in the portal because it keeps switching to my original work work account under my alias@microsoft.com address which doesn't have access. I think I tripped over an edge case bug in devops!! Can you remove my work address and add matt.connew at outlook instead?

**Comment by jongalloway** [comment]
@mconnew Removed work account and added outlook account. Once you accept I'll add you to the team.

**Comment by onovotny** [comment]
@mconnew I just added that account to the project admin of CoreWCF. Please confirm that it works for you and let me know how else I can help.

**Comment by mconnew** [comment]
@jongalloway, @onovotny, I've accepted the invite but I think I just fell down the same bug hole. My MSA has multiple email accounts, the primary account being one I created 25 years ago and not one I generally use publicly as I was a kid when I made it 😃. But I have an azure subscription tied to it, so I'm hitting the same problem again as it looks like it thinks there are two separate accounts and then realizes it's one but won't let me access CoreWCF from the primary email address. The place where I'm getting stuck is configuring the Azure Pipelines integration into the repo correctly. I'll have to follow up with the Azure Devops team tomorrow to see what's going on.

**Comment by jongalloway** [comment]
Ping me Weds if you're blocked and AzDO can't help, we can screen share or whatever and get it set up.

**Comment by mconnew** [comment]
@onovotny, @jongalloway, working with the Azure DevOps team, I've found a workaround for my auth issue, but now I'm being told I can't enable the integration because of the error "Sorry, this project cannot be used since you do not have permission to edit builds." Can you make sure I have the correct permissions on the devops project.

**Comment by onovotny** [comment]
Can you please loop us into the thread on email? We're both in the GAL. You should be a project admin (at least your outlook.com address is) so you should be able to do anything.

**Comment by mconnew** [comment]
I've finally got a decent pipeline set up and packages being created on merge. What's the situation with signing the packages? I presume they should be signed by a certificate owned by the foundation?

**Comment by onovotny** [comment]
Please create an issue (there's an issue template for it) requesting a Code Signing cert. It can take 1-2 weeks, depending on how fast the CA can process things.

Integrating into the pipeline can look something like this:

https://github.com/reactiveui/refit/blob/master/azure-pipelines.yml#L97-L141

**Comment by clairernovotny** [comment]
Closing due to age. Please reopen if there's still an issue.
