### ISSUE TITLE
Any point in re-applying?

### ISSUE THREAD

**Issue by FreddieMercurial** [dotnet-foundation/projects#201]
Since my application, some things have changed on the dotnet and foundation landscapes, but my health has remained poor. I'm deeply looking for a way to find like minded developers and show them the real potential of BrightChain and get them interested in helping me complete it which I am happy to PM on and will keep driving forward- but my health has me going at snails pace on the actual code by myself. I applied previously, was not given any real transparency about the process and got left on the back-burner and I'd turned down a commercial application/opportunity because I believe this project needs to be open source but also because I thought the foundation was already onboarding me.

I'd love to know your opinion on the https://github.com/BrightChain/BrightChain (non-functional, work in progress, substantially developed) project and whether I should reapply here or if you had suggestions where I could seek an audience?

**Comment by Perksey** [comment]
Currently, projects like BrightChain if they are not eligible for membership now they are put into the "Seed" section. It is an ongoing issue in the projects committee that they don't really know what to do with this column, but the idea is periodically the projects committee will review these projects and will reach out if they become eligible in the future. But again, this isn't really the case today.

Since you closed your original application, that can be misconstrued as you no longer being interested in .NET Foundation membership.

**I am not on the projects committee** (only the maintainers committee), but currently it looks like BrightChain would still not be eligible in my opinion based on:
- low number of contributors
- low usage metrics (no indication of it being used by external users, be that via stars, [repos](https://github.com/BrightChain/BrightChain/network/dependents), or downloads of published artifacts (of which you don't visibly have any))
- limited indicators of maturity (there being no release indicates it's still a work-in-progress and not established quite yet)

Again, if the "Seed" programme worked as expected, once those stop being the case and you hadn't closed your application theoretically you'd be hearing from the committee to onboard.

But generally projects coming into the DNF have functional releases, with modest adoption and recognition in their respective communities and have metrics supporting that.

I hope that answer helps until someone "official" comes a long (which could take time!)

**Comment by FreddieMercurial** [comment]
Yeah- I'm in that catch-22 phase where I think it's a great idea and am trying to get interest in developing it. It's therefore not usable yet. A lot of it is moving into a sub-project actually right now- though it's probably part of brightchain. I had hoped the foundation could help garner interest and see the potential in the project both for microsoft and the community and pitch in.
I wish there was a better way. I did have a disagreement with the process/and kind of lack of communication/lack of mutual respect. Changes were made and I wondered whether it was worth reapplying.
I appreciate the response.
