### ISSUE TITLE
https://dnfprojects.azurewebsites.net/ is not truly open-source

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/projects#92]
Hi all,

## Background

I was excited to see the metrics web site at https://dnfprojects.azurewebsites.net/ -- I think it provides a strong draft to build upon. I don't agree with the health criteria selected, but that's fine -- I appreciate that it provides a starting point for the conversation.

The first thing I wanted to do to celebrate this was to ensure that others could see the source code and where it lived. I [asked @sbwalker on Twitter](https://twitter.com/sjkilleen/status/1296925500904964105?s=20) where the source code was located, and he kindly supplied https://github.com/oqtane/DNF.Projects. 

I [submitted an issue](https://github.com/oqtane/DNF.Projects/issues/1) to try to update some text when I couldn't find the content in the source code. Shaun then clarified that the actual contents live in a database within a CMS component.

## Concern

I would suggest that the site at https://dnfprojects.azurewebsites.net does not, in its current state, meet the criteria for the spirit of an open-source project, in that I was unable to submit even a small text change as a PR. The community will be unable to contribute changes if content is hidden behind a CMS with a login.

## Seriously, this is not a dig at the creators.

I appreciate the group moving something forward and creating this initial version -- surely I have not done any such thing myself yet. It should be lauded. I also appreciate that you attempted to use a .NET Foundation project to produce the work.  

## What I propose (one option amongst many)

I don't like to raise a concern like this without offering at least a starting point for some alternatives.

* Data could be collected via an Azure Function definition, -- the functions could be stored in source code
* The azure function could use a KeyVault with a GitHub token
* Actions could be queued to run, and to pause whenever a token reaches an API limit, etc.
* The function data could still be stored in a database -- Cosmos, function-based SQL Azure, etc.
* These cloud definition files could be encapsulated in a Terraform file
* An open CI/CD build process could be constructed via GitHub Actions or Azure DevOps
* An API could be constructed to return the data, which could be heavily cached on read
* The web app could be a static web app (Statiq, Angular, Jekyll, something else) hosted on Azure SWA that hits the API during build or run time.
* Place all of this together in a repository at `dotnet-foundation/project-metrics` or similar.

What this would provide:

* Insight into all of the source code within a repository
* The ability to recreate the project by utilizing the build process and running Terraform apply in case someone wanted to explore it on their own (thus teaching others about these things in the process).
* The ability to change contents should anyone want to make a contribution
* No logins, etc. but the data is still protected to the extent you'd like it to be.

---

As always, I'm interested in your thoughts! Thank you for creating this app which sparked the discussion.

**Comment by sbwalker** [comment]
Thank you for your feedback. Its fairly normal in open source that once someone sees a solution in action, they will have opinions on ways it could be modified or how it could be implemented differently. In this particular case, it might be helpful to understand the original requirements.

The Project Committee was tracking the Github activity metrics outlined in the Project Charter manually using a spreadsheet and felt that an automated system would be a better option. So a solution was created based on a modular framework ( which is an existing .NET Foundation project ) and a custom module ( which was also published as an open source project ). The custom module contains a public dashboard, a secure management user interface, a database repository, and a scheduled job which runs daily and calls the Github API to retrieve data ( you can see the full functionality in the repo https://github.com/oqtane/DNF.Projects ). The solution was deployed to an Azure app service instance and has been running successfully for the past month.  

As noted in this issue description, there is currently one small item of text which is displayed at the top of the page in the main user interface that is dynamic content stored in the backend database and not static text embedded in the source code. We have already gone ahead and made the simple change to the site which was requested ( ie. we added "Check out the project on GitHub!" and included a link to the repo where the module resides ). Thank you for this suggestion.

Since the site is already satisfying the requirements of the Project Committee ( which is only focused on monitoring basic activity metrics ) it does seem very practical to rewrite the existing solution. That being said, we certainly do not want to discourage you from pursuing the solution you described. Based on recent conversations there certainly appears to be an opportunity to create a project/site which offers some more advanced analysis or insights... so we would like to encourage you to continue your efforts.
